### PR TITLE
(feat) implement working AJAX calls in curricula view

### PR DESCRIPTION
**Pull request by zhengcano**

### CODE REVIEW

**Comment by KalevRK** [comment]
Updates look good. I'm assuming that the request URL will need to be updated to work both locally or deployed in the future.

**Comment by zhengcano** [comment]
Yes. That's an easy fix that can be implemented when we're production/mvp ready

**Comment by MichaelRoberts214** [comment]
Would logical OR work here for putting either URL as the URL?

**Comment by zhengcano** [comment]
Not really, there's no ENV variable we can compare it to. I don't think it should be too difficult to implement, though.

**Pull request merged**
