### PR TITLE
(testing) Add unit test for creating curriculum.

### PR DESCRIPTION
**Pull request by KalevRK**

### CODE REVIEW

**Comment by KalevRK** [comment]
Sorry about the two commits. Ran into an issue with rebasing.

**Comment by wendy** [comment]
it's goup. :)

**Comment by zhengcano** [comment]
giphy

**Comment by MichaelRoberts214** [comment]
@KalevRK I know that feel
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Pull request merged**
