### PR TITLE
(fix) Topic view button in curriculum view now reroutes to the correct g...

### PR DESCRIPTION
**Pull request by MichaelRoberts214**
...raph view. Graph view bar channel name now displays the correct name

(fix) View Resource links in NodeView work after resource addition

(refactor) start work on d3 force in graph view

(fix) text no longer appears in the left corner

continue work on d3 graph

commit before --rebase

(fix) fix duplicate rendering bug of D3Graph SVG

(fix) text moves with circle nodes now in graph view

(feat) first circle is the largest

(feat) number of nodes in Graph View is dynamic now

(feat) make Graph View svg canvas resize with window width change

(feat) continue styling graph view

(refactor) start styling GraphView

(fix) fixed back button in course view

(fix) fix bug where topic view button in angular curricula links to javascript

(refactor) delete commented out extraneous code

(fix) graph view bar now says the correct channel name

### CODE REVIEW

**Comment by zhengcano** [comment]
looks ok

**Comment by MichaelRoberts214** [comment]
Gosh that submit message. I was so excited to show these bug fixes that I didn't delete any of this extraneous stuff.

**Comment by zhengcano** [comment]
extraneous is a big word... but I think that may be off topic

**Comment by MichaelRoberts214** [comment]
Oh you

**Pull request merged**
